name: workflow-ci-dev

on:
  push:
    branches:
      - dev
      - feature/**
  pull_request:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    env:
      SERVER_PORT: 5000
      DB_URL: jdbc:mysql://localhost:3308/studiozero?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_RESET_SECRET: ${{ secrets.JWT_RESET_SECRET }}
      EMAIL_USUARIO: ${{ secrets.EMAIL_USUARIO }}
      EMAIL_SENHA: ${{ secrets.EMAIL_SENHA }}
      RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      MYSQL_HOST: localhost
      MYSQL_PORT: 3308
      MYSQL_DATABASE: studiozero
      RABBITMQ_HOST: localhost
      RABBITMQ_PORT: 5672
      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Configurar JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Subir containers com Docker Compose
        run: |
          echo "Subindo containers MySQL e RabbitMQ..."
          docker compose up -d
          echo "Aguardando serviços ficarem prontos..."
          sleep 30
          docker ps -a

      - name: Rodar testes de integração
        env:
          SPRING_PROFILES_ACTIVE: test
          MYSQL_HOST: localhost
          MYSQL_PORT: 3308
          MYSQL_DATABASE: studiozero
          MYSQL_USER: root
          MYSQL_PASSWORD: studiozero
          RABBITMQ_USER: studiozero-admin
          RABBITMQ_PASSWORD: tudiozero-rmq-pass
          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: 5672
        run: mvn test -e -X

      - name: Derrubar containers
        if: always()
        run: docker compose down -v
